### ISSUE TITLE
Bump CI to GHC 7.10

### ISSUE THREAD

**Issue by mvdan** [tuura/plato#13]
Travis currently only has versions up to 7.8 available: https://github.com/travis-ci/travis-ci/issues/3785

We could semi-automatically install 7.10 as described in the issue, but we're not in desperate need of a newer version. This issue is just so that we remember to eventually switch `.travis.yml` to 7.10.

**Comment by snowleopard** [comment]
Switching to 7.10 is not urgent but may become necessary at some point.

**Comment by mvdan** [comment]
If it becomes necessary for CI we just have to check whether Travis has official support for it at that point. If it doesn't, we can then switch to manual installation as a temporary workaround.

**Comment by mvdan** [comment]
Some projects have successfully switched to 7.10, so not sure what's going on. I guess 7.10 is available after all.
