### ISSUE TITLE
No LICENSE file

### ISSUE THREAD

**Issue by mvdan** [tuura/plato#8]
I just noticed that none of our repos have a LICENSE file nor are stated to be under any specific license. That means that they are not free software, as per the GitHub rules if I recall correctly.

I would suggest the BSD 3-clause, which is a permissive license (similar to MIT or BSD 2-clause), but which also protects the names of the copyright holders and contributors. It's used in many open source projects nowadays like Tor and Go.

**Comment by snowleopard** [comment]
Done. Used a standard BSD 3-clause template. Feel free to propose changes if you like.

I'll add the same license in other projects as well.

**Comment by mvdan** [comment]
SGTM. As long as everyone is fine with giving up their copyright to you :)

**Comment by snowleopard** [comment]
@mvdan I don't think it is common to explicitly list all contributors in copyright lines -- is there a standard approach to this? Shall it be `Tuura team` instead? I admit I'm often confused as to how this should work.

**Comment by mvdan** [comment]
I'd go for `Tuura authors`, and then listing them in an `AUTHORS` file as name and e-mail.

See:

https://github.com/golang/go/blob/master/LICENSE
https://github.com/golang/go/blob/master/AUTHORS

I know this sounds overly complex, but it's really the easiest way to do it. Another way to do it would be to have a license header per-file with the copyright holders, which you can bet is more verbose and complicated.

I'll only contribute to this repo for now so I'm not worried myself about what you do with the other repos, but you might want to do the same.

**Comment by snowleopard** [comment]
> I'd go for `Tuura authors`, and then listing them in an `AUTHORS` file as name and e-mail.

This looks like a good solution, let's use it. (Apparently things get far more complicated when `AUTHORS` contains companies, which brings `CONTRIBUTORS` into play. Crazy.)

I wouldn't want to bother with per-file copyright holders.

**Comment by mvdan** [comment]
Yeah, there is also the world of CLAs and giving up copyright ownership, and things can get ugly.

**Comment by snowleopard** [comment]
OK, done.
@mvdan @jrbeaumont Please add your names and emails you'd like to use to `AUTHORS`.

**Comment by mvdan** [comment]
`Daniel Martí <mvdan@mvdan.cc>`

**Comment by jrbeaumont** [comment]
jonathan.r.beaumont@googlemail.com

I apologise I would do this myself but I am currently away without any decent access to a computer.

**Comment by snowleopard** [comment]
@jrbeaumont No problem, I added you to the list.

**Comment by snowleopard** [comment]
@mvdan I wonder what are the usual rules for qualifying as an author. If I go and add a comment to the Go project, that wouldn't be enough to suddenly get listed as an author, or would it?

**Comment by mvdan** [comment]
I'm not sure, actually, and it doesn't specify. Anyone having authored a commit seems like the easiest way to do it.

**Comment by snowleopard** [comment]
Somehow it doesn't feel right, because it devalues the list. But then almost everything about copyright & other IP issues feels wrong, so nothing surprising.
